src/ui/TableRichSelector.js
=> escape一下内容。

src/ui/css/spriteIconMixin.less
放弃使用est的mixin，100%的textindent在当前情境下不够。
=> 放弃使用est的mixin

src/mvc/StaticListData.js
StaticListData改为通过判断关键字段是否变化确定数据取向
=> StaticListData改为通过判断关键字段是否变化确定数据取向

src/mvc/StaticListData.js
=> 把cache方法释放成接口方法

src/mvc/FormAction.js, src/mvc/FormView.js
=> Add update confirm

src/mvc/FormModel.js
=> 拆分save和update方法

src/mvc/ListModel.js
=> 将列表多选单选类型处理逻辑独立到一个接口方法

src/mvc/BaseAction.js, src/mvc/ListView.js, src/util.js
=> 修复字符串对null的处理

src/ui/css/BoxGroup.less, src/ui/css/CheckBox.less, src/ui/css/main.less
=> 增加Checkbox自定义样式

src/mvc/RequestManager.js
方便去除业务中的`extension/ajax`
Fix #167
=> 独立RequestManager与ajax

src/ui/Uploader.js
=> 为Uploader添加扩展性，并移除sessionToken的逻辑

src/ui/css/spriteIconMixin.less
升级spriteIconMixin，增加对font-icon的支持。
=> 升级spriteIconMixin

src/ui/css/spriteIconMixin.less
=> 增加text-indent的重置

src/ui/TreeRichSelector.js
1. selectAll的逻辑由原来的只操作叶子节点改为遍历整棵树，操作所有节点
2.  父子节点同步方法拆解成两个方法，分别执行向上向下的同步操作
3. deleteAll的事件返回参数里，由返回一整颗树改为返回全部节点数组
4. getSelectedTree 方法修改成对2级以上树的支持
=> 修改TreeRichSelector的一些bug

src/ui/css/CheckBox.less
=> 修改checkbox的皮肤样式

src/mvc/StaticListData.js
=> 修改staticListData.filterData，返回深克隆后的查询结果

module.conf, package.json, src/mvc/BaseView.js, src/mvc/DetailModel.js, src/mvc/FormAction.js, src/mvc/FormModel.js, src/mvc/FormView.js, src/mvc/IoCActionFactory.js, src/mvc/ListAction.js, src/mvc/ListModel.js, src/mvc/SingleEntityModel.js, src/mvc/StaticListData.js, test/run.html
=> 使用新的promise

src/mvc/BaseView.js, src/mvc/FormAction.js, src/mvc/FormView.js
=> 修复waitConfirm接口

src/extension/mvc.js
=> 修复添加容器class的时机

src/ui/css/spriteIconMixin.less
=> 增加对line-height控制居中的支持

src/mvc/BaseView.js, src/mvc/DetailView.js, src/mvc/FormView.js, src/mvc/ListView.js
=> 抽象popDrawerAction方法

src/ui/css/Button.less
=> 修复eicons变量名

src/util.js
`underscore`的`templateSettings`是不会继承的……
=> 修复util.template方法

src/mvc/FormView.js, src/util.js, test/run.html, test/spec/util.spec.js
=> getEntity支持深层属性

src/mvc/BaseAction.js, src/mvc/BaseModel.js, src/mvc/DetailModel.js, src/mvc/EntityValidator.js, src/mvc/FormAction.js, src/mvc/FormModel.js, src/mvc/ListModel.js, src/mvc/RequestManager.js, src/mvc/handler/RedirectSubmitHandler.js, src/mvc/handler/SubmitHandler.js, src/mvc/handler/ToastSubmitHandler.js
添加set方法的注释，将setGlobalData移入基类，补充一个scope逻辑
=> 添加set方法的注释，将setGlobalData移入基类，补充一个scope逻辑

src/ui/Uploader.js
=> 修正清除文件时accept属性丢失

src/mvc/ListView.js, src/ui/extension/AutoSubmit.js
- 移除对视图控件状态的依赖逻辑
- 筛选状态数据从 model 中获得
=> 基础库增加对即时筛选的支持

src/extension/ui.js
=> Fix ui extension

src/mvc/ListView.js
https://github.com/ecomfe/ub-ria/issues/262
=> 列表mvc增加查看报告command，修改command事件处理的逻辑

src/mvc/list/ListAction.js
=> 在列表查询条件更新时保留URL中的非查询参数

src/mvc/form/FormAction.js, src/mvc/form/FormView.js, src/tpl.js, src/ui/scroll/Scroll.js, src/ui/scroll/Scroll.less
=> 增加Scroll控件，控制页面的自动向上滚动
